// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId           string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content          string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp        int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EncryptedContent []byte                 `protobuf:"bytes,6,opt,name=encrypted_content,json=encryptedContent,proto3" json:"encrypted_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetEncryptedContent() []byte {
	if x != nil {
		return x.EncryptedContent
	}
	return nil
}

type RoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomRequest) Reset() {
	*x = RoomRequest{}
	mi := &file_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequest) ProtoMessage() {}

func (x *RoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequest.ProtoReflect.Descriptor instead.
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *RoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RoomRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Peers         []*Peer                `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	mi := &file_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *RoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RoomResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RoomResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *Peer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Peer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Peer) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SendMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoomId           string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EncryptedContent []byte                 `protobuf:"bytes,2,opt,name=encrypted_content,json=encryptedContent,proto3" json:"encrypted_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_proto_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMessage) GetEncryptedContent() []byte {
	if x != nil {
		return x.EncryptedContent
	}
	return nil
}

type ReceiveMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username         string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	EncryptedContent []byte                 `protobuf:"bytes,4,opt,name=encrypted_content,json=encryptedContent,proto3" json:"encrypted_content,omitempty"`
	Timestamp        int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReceiveMessage) Reset() {
	*x = ReceiveMessage{}
	mi := &file_proto_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessage) ProtoMessage() {}

func (x *ReceiveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessage.ProtoReflect.Descriptor instead.
func (*ReceiveMessage) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReceiveMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReceiveMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReceiveMessage) GetEncryptedContent() []byte {
	if x != nil {
		return x.EncryptedContent
	}
	return nil
}

func (x *ReceiveMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Message
	//	*ServerMessage_PeerJoined
	//	*ServerMessage_PeerLeft
	//	*ServerMessage_RoomResponse
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetMessage() *ReceiveMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ServerMessage) GetPeerJoined() *PeerJoined {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PeerJoined); ok {
			return x.PeerJoined
		}
	}
	return nil
}

func (x *ServerMessage) GetPeerLeft() *PeerLeft {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PeerLeft); ok {
			return x.PeerLeft
		}
	}
	return nil
}

func (x *ServerMessage) GetRoomResponse() *RoomResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RoomResponse); ok {
			return x.RoomResponse
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Message struct {
	Message *ReceiveMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ServerMessage_PeerJoined struct {
	PeerJoined *PeerJoined `protobuf:"bytes,2,opt,name=peer_joined,json=peerJoined,proto3,oneof"`
}

type ServerMessage_PeerLeft struct {
	PeerLeft *PeerLeft `protobuf:"bytes,3,opt,name=peer_left,json=peerLeft,proto3,oneof"`
}

type ServerMessage_RoomResponse struct {
	RoomResponse *RoomResponse `protobuf:"bytes,4,opt,name=room_response,json=roomResponse,proto3,oneof"`
}

func (*ServerMessage_Message) isServerMessage_Payload() {}

func (*ServerMessage_PeerJoined) isServerMessage_Payload() {}

func (*ServerMessage_PeerLeft) isServerMessage_Payload() {}

func (*ServerMessage_RoomResponse) isServerMessage_Payload() {}

type PeerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerJoined) Reset() {
	*x = PeerJoined{}
	mi := &file_proto_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerJoined) ProtoMessage() {}

func (x *PeerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerJoined.ProtoReflect.Descriptor instead.
func (*PeerJoined) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{7}
}

func (x *PeerJoined) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PeerJoined) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PeerJoined) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type PeerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerLeft) Reset() {
	*x = PeerLeft{}
	mi := &file_proto_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerLeft) ProtoMessage() {}

func (x *PeerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerLeft.ProtoReflect.Descriptor instead.
func (*PeerLeft) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{8}
}

func (x *PeerLeft) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_JoinRoom
	//	*ClientMessage_SendMessage
	//	*ClientMessage_LeaveRoom
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoinRoom() *RoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *ClientMessage) GetSendMessage() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ClientMessage) GetLeaveRoom() *RoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_JoinRoom struct {
	JoinRoom *RoomRequest `protobuf:"bytes,1,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type ClientMessage_SendMessage struct {
	SendMessage *SendMessage `protobuf:"bytes,2,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type ClientMessage_LeaveRoom struct {
	LeaveRoom *RoomRequest `protobuf:"bytes,3,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

func (*ClientMessage_JoinRoom) isClientMessage_Payload() {}

func (*ClientMessage_SendMessage) isClientMessage_Payload() {}

func (*ClientMessage_LeaveRoom) isClientMessage_Payload() {}

var File_proto_chat_proto protoreflect.FileDescriptor

const file_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x10proto/chat.proto\x12\x04chat\"\xb0\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12+\n" +
	"\x11encrypted_content\x18\x06 \x01(\fR\x10encryptedContent\"\x96\x01\n" +
	"\vRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"}\n" +
	"\fRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x05peers\x18\x03 \x03(\v2\n" +
	".chat.PeerR\x05peers\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"Z\n" +
	"\x04Peer\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"S\n" +
	"\vSendMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12+\n" +
	"\x11encrypted_content\x18\x02 \x01(\fR\x10encryptedContent\"\xa0\x01\n" +
	"\x0eReceiveMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12+\n" +
	"\x11encrypted_content\x18\x04 \x01(\fR\x10encryptedContent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xeb\x01\n" +
	"\rServerMessage\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x14.chat.ReceiveMessageH\x00R\amessage\x123\n" +
	"\vpeer_joined\x18\x02 \x01(\v2\x10.chat.PeerJoinedH\x00R\n" +
	"peerJoined\x12-\n" +
	"\tpeer_left\x18\x03 \x01(\v2\x0e.chat.PeerLeftH\x00R\bpeerLeft\x129\n" +
	"\rroom_response\x18\x04 \x01(\v2\x12.chat.RoomResponseH\x00R\froomResponseB\t\n" +
	"\apayload\"`\n" +
	"\n" +
	"PeerJoined\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"#\n" +
	"\bPeerLeft\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb8\x01\n" +
	"\rClientMessage\x120\n" +
	"\tjoin_room\x18\x01 \x01(\v2\x11.chat.RoomRequestH\x00R\bjoinRoom\x126\n" +
	"\fsend_message\x18\x02 \x01(\v2\x11.chat.SendMessageH\x00R\vsendMessage\x122\n" +
	"\n" +
	"leave_room\x18\x03 \x01(\v2\x11.chat.RoomRequestH\x00R\tleaveRoomB\t\n" +
	"\apayloadB\x13Z\x11Void/proto/chatpbb\x06proto3"

var (
	file_proto_chat_proto_rawDescOnce sync.Once
	file_proto_chat_proto_rawDescData []byte
)

func file_proto_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)))
	})
	return file_proto_chat_proto_rawDescData
}

var file_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_chat_proto_goTypes = []any{
	(*Message)(nil),        // 0: chat.Message
	(*RoomRequest)(nil),    // 1: chat.RoomRequest
	(*RoomResponse)(nil),   // 2: chat.RoomResponse
	(*Peer)(nil),           // 3: chat.Peer
	(*SendMessage)(nil),    // 4: chat.SendMessage
	(*ReceiveMessage)(nil), // 5: chat.ReceiveMessage
	(*ServerMessage)(nil),  // 6: chat.ServerMessage
	(*PeerJoined)(nil),     // 7: chat.PeerJoined
	(*PeerLeft)(nil),       // 8: chat.PeerLeft
	(*ClientMessage)(nil),  // 9: chat.ClientMessage
}
var file_proto_chat_proto_depIdxs = []int32{
	3, // 0: chat.RoomResponse.peers:type_name -> chat.Peer
	5, // 1: chat.ServerMessage.message:type_name -> chat.ReceiveMessage
	7, // 2: chat.ServerMessage.peer_joined:type_name -> chat.PeerJoined
	8, // 3: chat.ServerMessage.peer_left:type_name -> chat.PeerLeft
	2, // 4: chat.ServerMessage.room_response:type_name -> chat.RoomResponse
	1, // 5: chat.ClientMessage.join_room:type_name -> chat.RoomRequest
	4, // 6: chat.ClientMessage.send_message:type_name -> chat.SendMessage
	1, // 7: chat.ClientMessage.leave_room:type_name -> chat.RoomRequest
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_chat_proto_init() }
func file_proto_chat_proto_init() {
	if File_proto_chat_proto != nil {
		return
	}
	file_proto_chat_proto_msgTypes[6].OneofWrappers = []any{
		(*ServerMessage_Message)(nil),
		(*ServerMessage_PeerJoined)(nil),
		(*ServerMessage_PeerLeft)(nil),
		(*ServerMessage_RoomResponse)(nil),
	}
	file_proto_chat_proto_msgTypes[9].OneofWrappers = []any{
		(*ClientMessage_JoinRoom)(nil),
		(*ClientMessage_SendMessage)(nil),
		(*ClientMessage_LeaveRoom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_proto = out.File
	file_proto_chat_proto_goTypes = nil
	file_proto_chat_proto_depIdxs = nil
}
