// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToRoom(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToRoom'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GenerateRoomID() {
  return window['go']['main']['App']['GenerateRoomID']();
}

export function GetMyPublicKeyFingerprint() {
  return window['go']['main']['App']['GetMyPublicKeyFingerprint']();
}

export function GetPeerFingerprint(arg1) {
  return window['go']['main']['App']['GetPeerFingerprint'](arg1);
}

export function GetPeerKeyFingerprint(arg1) {
  return window['go']['main']['App']['GetPeerKeyFingerprint'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetPeerFingerprint(arg1, arg2) {
  return window['go']['main']['App']['SetPeerFingerprint'](arg1, arg2);
}
