// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToRoom(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Disconnect():Promise<void>;

export function GenerateRoomID():Promise<string>;

export function GetMyPublicKeyFingerprint():Promise<string>;

export function GetPeerFingerprint(arg1:string):Promise<string>;

export function GetPeerKeyFingerprint(arg1:string):Promise<string>;

export function SendMessage(arg1:string):Promise<void>;

export function SetPeerFingerprint(arg1:string,arg2:string):Promise<void>;
